## Задание 1

In [54]:
import numpy as np

In [55]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [56]:
mean_a = a.mean(axis = 1)
mean_a

array([2. , 8.4])

## Задание 2

In [57]:
a_centered = a - mean_a.reshape(2,1)
a_centered

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

## Задание 3

In [58]:
a_centered_sp = a_centered.dot(a_centered.T)

In [59]:
a_centered_sp / (a_centered.shape[1]-1)

array([[1. , 2. ],
       [2. , 4.3]])

## Задание 4

In [60]:
np.cov(a.transpose(), y=None,
    rowvar=True,
    bias=False,
    ddof=None,
    fweights=None,
    aweights=None)

array([[12.5, 15. , 20. , 17.5, 15. ],
       [15. , 18. , 24. , 21. , 18. ],
       [20. , 24. , 32. , 28. , 24. ],
       [17.5, 21. , 28. , 24.5, 21. ],
       [15. , 18. , 24. , 21. , 18. ]])